---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hasura-extra-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://hasura-extra.github.io/hasura-extra
  timeout: 3m
