---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - stakater-charts.yaml
  - k8s-gateway-charts.yaml
  - longhorn-charts.yaml
  - authentik-charts.yaml
  - kubernetes-stable-charts.yaml
  - dex-charts.yaml
  - nicholaswilde.yaml
  - authelia-charts.yaml
  - node-feature-discovery-charts.yaml
  - vernemq-charts.yaml
  - hajimari-charts.yaml
  - metrics-server-charts.yaml
  - codecentric-charts.yaml
  - hasura-extra-charts.yaml
  - dysnix-charts.yaml
  - metallb-charts.yaml
  - oauth2-proxy.yaml
  - grafana.yaml
  - bytebase.yaml
  - pgadmin.yaml
  - prometheus-community-charts.yaml
  - bjw-s.yaml
  - openfaas-charts.yaml
  - fission-charts.yaml
  - postgrest-charts.yaml
  - cetic-charts.yaml
  - gabe565.yaml
  - crunchydata.yaml
  - groundhog2k.yaml
  - mariadb-operator.yaml
  - kedacore.yaml
  - tooljet-charts.yaml
  - emqx.yaml
  - intel.yaml
